export type ArchiveLevel = 'fast' | 'normal' | 'max'

export interface BatOptions {
  /** 预设源路径，空则脚本运行时交互输入（本工具默认留空，靠拖拽） */
  src: string
  /** 预设输出 .7z 路径，空则自动「源名_时间戳.7z」 */
  out: string
  level: ArchiveLevel
  encryptNames: boolean
}

export interface BatSection {
  /** 区块标题（脚本逐行解析用） */
  title: string
  /** 面向用户的解释：这一段在干什么、为什么这样写是对的 */
  note: string
  /** 该区块的原始行（已转义、已插值）；逐区块拼接即 buildBat 产物 */
  code: string[]
}

const MX: Record<ArchiveLevel, string> = { fast: '1', normal: '5', max: '9' }

/** cmd 的赋值语句里 `%` 要写成 `%%` 才是字面量，否则会被当成变量展开 */
function escBat(s: string): string {
  return s.replace(/%/g, '%%')
}

/**
 * 脚本被切成若干语义区块，每块带面向用户的解释。
 * buildBat 只是把这些区块拼起来 —— 展示的代码和下载的代码是同一份，永不漂移。
 *
 * 设计约束：脚本正文保持纯 ASCII（注释/提示全用英文）。cmd 读批处理默认按系统
 * 编码（中文系统是 GBK），UTF-8 中文注释会乱码甚至被当成命令执行（实测踩坑）。
 * 路径不写进脚本（运行时拖拽/交互输入，走系统编码），所以脚本可以做到纯 ASCII，
 * 任何语言系统的 Windows 都能正确解析。
 */
export function batSections(o: BatOptions): BatSection[] {
  const src = escBat(o.src)
  const out = escBat(o.out)
  const mx = MX[o.level]
  const mhe = o.encryptNames ? 'on' : 'off'

  const srcLine = src ? [`if "%SRC%"=="" set "SRC=${src}"`] : []
  const outLine = out ? [`set "OUT=${out}"`] : []

  return [
    {
      title: '头部：不 echo 命令，开启延迟展开',
      note: '脚本正文刻意用英文，避免批处理编码歧义——cmd 默认按系统编码读文件，中文系统的 UTF-8 中文注释会被当成命令报错。中文说明都在这个网页上。setlocal enabledelayedexpansion 开启延迟展开，让括号块里能安全使用 !TS! 这类变量。',
      code: [
        '@echo off',
        'rem Secure 7z archive tool - generated by tools.tobenot.top',
        'rem AES-256 encryption + encrypted headers (file names hidden too)',
        'rem Password entered interactively: no echo, no shell history',
        'rem Usage: double-click and type a path, or drag a file/folder onto this script',
        'setlocal enabledelayedexpansion',
      ],
    },
    {
      title: '自动找 7-Zip：装在哪都能跑',
      note: '优先用 PATH 里的 7z，其次查常见安装目录 %ProgramFiles%\\7-Zip。找不到就明确报错并给出下载链接，不会出现"7z 不是内部或外部命令"这种半懂不懂的报错。',
      code: [
        'set "SZ="',
        'where 7z >nul 2>nul && set "SZ=7z"',
        'if not defined SZ if exist "%ProgramFiles%\\7-Zip\\7z.exe" set "SZ=%ProgramFiles%\\7-Zip\\7z.exe"',
        'if not defined SZ (',
        '    echo [ERROR] 7-Zip not found. Install it first: https://www.7-zip.org/',
        '    pause & exit /b 1',
        ')',
      ],
    },
    {
      title: '源路径：拖进去最省事，双击也能手动输入',
      note: '把文件/文件夹直接拖到脚本图标上，%~1 会自动带上路径（拖拽是这条链路的主力用法）。双击运行时手动输入路径，输入带引号会被剥掉。路径不存在会在压缩前停下、给你再输入一次的机会。路径本身不会写进脚本，所以脚本能保持纯 ASCII。',
      code: [
        'rem ---- Source path: dragged arg wins, otherwise prompt below ----',
        'set "SRC=%~1"',
        ...srcLine,
        'if defined SRC set "SRC=%SRC:"=%"',
        'if not exist "%SRC%" (',
        '    echo [ERROR] Path not found: %SRC%',
        '    set /p "SRC=Drag a file/folder onto this script, or type a path: "',
        '    set "SRC=!SRC:"=!"',
        '    if not exist "!SRC!" (',
        '        echo [ERROR] Still not found. Exiting.',
        '        pause & exit /b 1',
        '    )',
        ')',
      ],
    },
    {
      title: '去尾反斜杠：取文件夹名才准',
      note: '文件夹路径结尾的反斜杠会让 %%~nF 取不到文件夹名（变成空），这里循环剥掉，保证自动输出名正确。',
      code: [
        'rem ---- Strip trailing backslash so the folder name can be derived ----',
        ':trim',
        'if "%SRC:~-1%"=="\\" set "SRC=%SRC:~0,-1%" & goto trim',
      ],
    },
    {
      title: '输出路径：不指定就「源名_时间戳.7z」',
      note: '自动放在源同目录，命名「源名_时间戳.7z」。时间戳保证重复压缩不会误追加进旧包（把两个密码不同的包混在一起）也不会覆盖。文件名由 PowerShell 取，不受系统日期格式影响。',
      code: [
        'rem ---- Output path: preset, or <source-name>_<timestamp>.7z ----',
        ...outLine,
        'if "%OUT%"=="" (',
        '    for /f "usebackq delims=" %%T in (`powershell -NoProfile -Command "Get-Date -Format \'yyyyMMdd_HHmmss\'"`) do set "TS=%%T"',
        '    for %%F in ("%SRC%") do set "OUT=%%~dpF%%~nF_!TS!.7z"',
        ')',
      ],
    },
    {
      title: '加密压缩命令：核心安全都在这一行',
      note: '-p 交互式收密码（不回显、不进命令行历史、不写进脚本），密码只在你脑子里。 -mhe=on 加密文件头，连文件名都看不见，ZIP 的 AES 都做不到。 -mx=' + mx + ' 压缩级别，-m0=lzma2 是 7z 默认算法，配 AES-256。压缩失败时 errorlevel 1 会停下报错，不会假装成功。',
      code: [
        'echo.',
        'echo Source: %SRC%',
        'echo Output: %OUT%',
        'echo.',
        `"%SZ%" a -t7z -p -mhe=${mhe} -mx=${mx} -m0=lzma2 "%OUT%" "%SRC%"`,
        'if errorlevel 1 (',
        '    echo [ERROR] Compression failed.',
        '    pause & exit /b 1',
        ')',
      ],
    },
    {
      title: '收尾：看清结果再关',
      note: '完成后显示输出路径，pause 让窗口停住，双击运行时能看到结果不会一闪而过。解压需同一密码，忘记密码 = 数据永久丢失 —— 7-Zip 没有后门。',
      code: [
        'echo.',
        'echo [DONE] Created: %OUT%',
        'echo Tip: unpack with the same password. Forgotten password = permanent loss; 7-Zip has no backdoor.',
        'pause',
      ],
    },
  ]
}

/** cmd 解析器对 LF-only 批处理里的 & / && 会解析出错，必须用 CRLF 换行 */
export function buildBat(o: BatOptions): string {
  return batSections(o)
    .map((s) => s.code.join('\r\n'))
    .join('\r\n\r\n') + '\r\n'
}
